### ISSUE TITLE
Bot requires update

### ISSUE THREAD

**Issue by leonard-thieu** [DefinitelyTyped/definition-header#18]
@vvakame, I've made labels optional and fixed an issue with getting the package name from files in subdirectories to fix the issue with parsing https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18767. Could you pull in these changes to the bot?

**Comment by vvakame** [comment]
ah, okey.
When we want to update the bot, we should push new commit to https://github.com/DefinitelyTyped/dt-review-bot . Circle CI will update it automatically.
I want to add you to some npm package owner.
what is your account of npm?
e.g.) https://www.npmjs.com/~vvakame <- this is me!

**Comment by leonard-thieu** [comment]
https://www.npmjs.com/~leonard-thieu

**Comment by vvakame** [comment]
I added you to https://www.npmjs.com/package/definition-header and https://www.npmjs.com/package/dt-review-tool . 👍 
You have write permission to dt-review-bot repository already.

**Comment by vvakame** [comment]
```
$ npm run build
$ npm run test
$ (modify package.json's version)
$ git tag vX.X.X
$ npm publish
$ git push && git push --tags
```
